name: muna_match
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2        # Camera & Gallery
  geolocator: ^9.0.2          # Location permissions
  record: ^5.0.0              # Voice recording
  audioplayers: ^6.1.0        # Play recorded audio
  path_provider: ^2.1.3       # Save recorded files
  permission_handler: ^11.3.1 # Manage runtime permissions (mic, storage, camera)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/Apple.png
    - assets/images/google.png
    - assets/images/characters.png
    - assets/images/logo2.png
    - assets/images/women.png
    - assets/images/men.png
    - assets/images/name.png  
    - assets/images/birthday.png
    - assets/images/married.png
    - assets/images/know_someone.png 
    - assets/images/curious.png
    - assets/images/couple.png
    - assets/images/spy.png
    - assets/images/Phone_mockup.png
    - assets/images/sample_user.png
    - assets/images/bismillah.png
    - assets/images/location.png
    - assets/images/profile_image.png
    - assets/images/not_boosted_badge.png
    - assets/images/eye_icon.png
    - assets/images/like.png
    - assets/images/dislike.png
    - assets/images/boost.png
    - assets/images/marriage_icon.png
    - assets/images/explore_icon.png
    - assets/images/social_icon.png
    - assets/images/chat_icon.png
    - assets/images/menu_icon.png
    - assets/images/profile.png
    - assets/images/Ali.png
    - assets/images/Muhammad.png
    - assets/images/Ezdan.png
    - assets/images/Mehmet.png
